# Generated by Django 4.2 on 2025-05-26 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='penalty_until',
            field=models.DateField(blank=True, null=True),
        ),
    ]
