# Generated by Django 5.2.1 on 2025-05-26 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myadmin", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="loan",
            name="bookID",
        ),
        migrations.DeleteModel(
            name="LibraryInfo",
        ),
        migrations.RemoveField(
            model_name="loan",
            name="userID",
        ),
        migrations.DeleteModel(
            name="Notice",
        ),
        migrations.RemoveField(
            model_name="reservation",
            name="userID",
        ),
        migrations.RemoveField(
            model_name="user",
            name="groups",
        ),
        migrations.RemoveField(
            model_name="user",
            name="user_permissions",
        ),
        migrations.DeleteModel(
            name="Book",
        ),
        migrations.DeleteModel(
            name="Loan",
        ),
        migrations.DeleteModel(
            name="Reservation",
        ),
        migrations.DeleteModel(
            name="User",
        ),
    ]
