# Generated by Django 5.2.1 on 2025-05-24 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="LibraryInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "day",
                    models.CharField(
                        choices=[
                            ("Mon", "Monday"),
                            ("Tue", "Tuesday"),
                            ("Wed", "Wednesday"),
                            ("Thu", "Thursday"),
                            ("Fri", "Friday"),
                            ("Sat", "Saturday"),
                            ("Sun", "Sunday"),
                        ],
                        max_length=10,
                        unique=True,
                    ),
                ),
                ("open_time", models.TimeField()),
                ("close_time", models.TimeField()),
            ],
        ),
    ]
